name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64
    strategy:
      matrix:
        python-version:
          - cp38-cp38
    steps:
      - uses: actions/checkout@v1
      - name: Set target Python version PATH
        run: echo "::add-path::/opt/python/${{ matrix.python-version }}/bin"
      - name: setup script
        run: .github/workflows/scripts/setup.sh
      - name: test cmake
        run: which cmake; cmake --version
      - name: test protobuf
        run: which protoc; protoc --version
