name: Test manylinux2014

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: true
      - name: Test
        run: echo "Done"
